language: python
python:
  - 3.6

# Update pip to the latest version
before_install:
  - python --version
  - pip install -U pip

install:
  - pip install -r requirements.txt

script:
  - python -m unittest test/multiplication_tests.py

deploy:
  provider: pypi
  username: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJGQ0MzVhMTExLWNjOTgtNGVhNC04NmEwLWVmODBjYmIwMzViNAACKlszLCI0YmExYTA4NS05Y2I3LTQzMDQtOTViNS00NGQ5NjJjYTFhZTYiXQAABiCmfTHNSX6OKLSdKfuE49VxiPy9ho6pFoGAa0cioF4m_g"
  on:
    branch: master